#include <check.h>
#include <ctype.h>
#include <float.h>
#include <stdio.h>
#include <string.h>
#include <wchar.h>

#include "../my_string.h"

Suite *suite_memcpy();
Suite *suite_strerror();
Suite *suite_strncpy();
Suite *suite_strlen();
Suite *suite_memset();
Suite *suite_memchr();
Suite *suite_memcmp();
Suite *suite_strncat();
Suite *suite_strncmp();
Suite *suite_strchr();
Suite *suite_strcspn();
Suite *suite_strrchr();
Suite *suite_strstr();
Suite *suite_strpbrk();
Suite *suite_strtok();
Suite *suite_to_upper();
Suite *suite_to_lower();
Suite *suite_insert();
Suite *suite_trim();
Suite *suite_sprintf();
Suite *suite_sscanf();